// <auto-generated />
using System;
using ByMyPc.Postgresql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ByMyPc.Postgresql.Migrations
{
    [DbContext(typeof(PgContext))]
    [Migration("20260902183252_AddIndexToCPUName")]
    partial class AddIndexToCPUName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ByMyPc.Postgresql.Models.CpuDbModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count_Cores")
                        .HasColumnType("integer");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("CPUs");
                });

            modelBuilder.Entity("ByMyPc.Postgresql.Models.GpuDbModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VideoMemorySize")
                        .HasColumnType("integer");

                    b.Property<int>("VideoSlot")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("GPUs");
                });

            modelBuilder.Entity("ByMyPc.Postgresql.Models.HDDDbModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GbSize")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("connector")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("HDDs");
                });

            modelBuilder.Entity("ByMyPc.Postgresql.Models.MotherboardDbModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IntegrationGpu")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxCpuFrequency")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRamFrequency")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRamSlot")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VideoSlot")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("Motherboards");
                });

            modelBuilder.Entity("ByMyPc.Postgresql.Models.PSUDbModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PowerWatt")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("PSUDbModel");
                });

            modelBuilder.Entity("ByMyPc.Postgresql.Models.PcDbModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CpuId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GpuId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MotherboardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PSUId")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("CpuId");

                    b.HasIndex("GpuId");

                    b.HasIndex("MotherboardId");

                    b.HasIndex("PSUId");

                    b.ToTable("PCs");
                });

            modelBuilder.Entity("ByMyPc.Postgresql.Models.PcHddDbModel", b =>
                {
                    b.Property<Guid>("PcId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HddId")
                        .HasColumnType("uuid");

                    b.HasKey("PcId", "HddId");

                    b.HasIndex("HddId");

                    b.ToTable("PcHdds");
                });

            modelBuilder.Entity("ByMyPc.Postgresql.Models.PcRamDbModel", b =>
                {
                    b.Property<Guid>("PcId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.HasKey("PcId", "RamId", "Slot");

                    b.HasIndex("RamId");

                    b.ToTable("PcRams");
                });

            modelBuilder.Entity("ByMyPc.Postgresql.Models.RamDbModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DDRType")
                        .HasColumnType("integer");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("RAMs");
                });

            modelBuilder.Entity("ByMyPc.Postgresql.Models.PcDbModel", b =>
                {
                    b.HasOne("ByMyPc.Postgresql.Models.CpuDbModel", "Cpu")
                        .WithMany()
                        .HasForeignKey("CpuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ByMyPc.Postgresql.Models.GpuDbModel", "Gpu")
                        .WithMany()
                        .HasForeignKey("GpuId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ByMyPc.Postgresql.Models.MotherboardDbModel", "Motherboard")
                        .WithMany()
                        .HasForeignKey("MotherboardId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ByMyPc.Postgresql.Models.PSUDbModel", "PSU")
                        .WithMany()
                        .HasForeignKey("PSUId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cpu");

                    b.Navigation("Gpu");

                    b.Navigation("Motherboard");

                    b.Navigation("PSU");
                });

            modelBuilder.Entity("ByMyPc.Postgresql.Models.PcHddDbModel", b =>
                {
                    b.HasOne("ByMyPc.Postgresql.Models.HDDDbModel", "Hdd")
                        .WithMany()
                        .HasForeignKey("HddId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ByMyPc.Postgresql.Models.PcDbModel", "Pc")
                        .WithMany("HDDs")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hdd");

                    b.Navigation("Pc");
                });

            modelBuilder.Entity("ByMyPc.Postgresql.Models.PcRamDbModel", b =>
                {
                    b.HasOne("ByMyPc.Postgresql.Models.PcDbModel", "Pc")
                        .WithMany("Rams")
                        .HasForeignKey("PcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByMyPc.Postgresql.Models.RamDbModel", "Ram")
                        .WithMany()
                        .HasForeignKey("RamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pc");

                    b.Navigation("Ram");
                });

            modelBuilder.Entity("ByMyPc.Postgresql.Models.PcDbModel", b =>
                {
                    b.Navigation("HDDs");

                    b.Navigation("Rams");
                });
#pragma warning restore 612, 618
        }
    }
}
